config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tweets
  root "tweets#index"
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    page = (params[:page] || 0).to_i
    tweets = Tweet.limit(10).offset(page * 10)
    render locals: { tweets: tweets, page: page }
  end

  def show
    render template: 'tweets/show.html.erb', locals: { tweet: Tweet.find(params[:id]) }
  end

  def new
    user_options = User.order(name: :asc).map { |u| [u.name, u.id] }
    render locals: {
      tweet: Tweet.new,
      user_options: user_options
    }
  end

  def create
    tweet = Tweet.new
    tweet.message = params.fetch(:tweet).fetch(:message)
    tweet.user_id = params.fetch(:tweet).fetch(:user_id)
    if tweet.save
      redirect_to tweet_path(tweet)
    else
      redirect_to tweets_path
    end
  end

  def update
  end

  def destroy
    if Tweet.exists?(params[:id])
      Tweet.destroy(params[:id])
    end
    redirect_to tweets_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    render template: 'users/index.html.erb', locals: { users: User.all }
  end

  def show
    render template: 'users/show.html.erb', locals: { user: User.find(params[:id]) }
  end

  def new

  end

  def create

  end

  def update

  end

  def destroy

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>&iexcl;&iexcl;HoW Doge!! </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <nav>
    <ul>
      <li><%= link_to 'Home', root_url %></li>
      <li><%= link_to 'Arfs', tweets_path %></li>
      <li><%= link_to 'Doges', users_path %></li>
      <li><%= link_to 'Make Arf!', new_tweet_path %></li>
    </ul>
  </nav>
</header>


<%= yield %>

</body>
</html>

app/views/tweets/index.html.erb
<h1>&hearts; Such Arf! &hearts; &hearts; </h1>

<ul>
<% tweets.each do |tweet| %>
  <li>id: <%= tweet.id %> tweet: <%= tweet.message %></li>
<% end %>
</ul>

<%= link_to('< Prev Page', root_path(page: page - 1)) %>
<%= link_to('Next Page >', root_path(page: page + 1)) %>

app/views/tweets/new.html.erb
<h2>New Arf Woof </h2>

<% if tweet.errors.any? %>
  <% tweet.errors.messages.each do |att, err_msg| %>
    <p class='error'><strong><%= att %>:</strong> <%= err_msg.join %></p>
  <% end %>
<% end %>

<%= form_for(tweet) do |f| %>
  <p>
  <%= f.label :message %>
  <%= f.text_field :message %>
  </p>
  <p>
  <%= f.label :user_id %>
  <%= f.select :user_id, user_options, include_blank: true %>
  </p>
  <%= f.submit %>
<% end %>

app/views/tweets/show.html.erb
<h1>Individual Tweet</h1>

<p>Tweet: <%= tweet.message %></p>

app/views/users/index.html.erb
<h1>Users</h1>

<% users.each do |user|%>
  <p><%=link_to("#{user.name}", user_path(user))%></p>
<%end%>

app/views/users/show.html.erb
<h1>Users</h1>

<p>User: <%= user.name %></p>